#!/bin/sh
# hq-dump

# Simple means of dumping hq journal files to get specifics for JMS messages.
# An example of where this can be useful is finding the future delivery date
# for messages that have the _HQ_SCHED_DELIVERY property set.

# Note that this was used with the jboss-fsw-installer-6.0.0.GA-redhat-4.jar
# distribution of Fuse Service Works.

# You may need to change the jar file versions found below and should be able
# to find them below the BASE directory.

# the output of the record fields that i am interested in (message id, delivery count, date of next delivery attempt)
# should look something like this:
# 7254874 9 Thu Nov 27 22:42:36 EST 2014

function usage() {
    echo "Usage: $0 [ JBOSS_HOME ]"
}

# to output all fields use this
function outputRaw() {
    java -cp $JARS org.hornetq.core.persistence.impl.journal.PrintData $DATA/messagingbindings $DATA/messagingjournal
}

# to output just the message id and readable delivery date use this
function outputSched() {
java -cp $JARS org.hornetq.core.persistence.impl.journal.PrintData $DATA/messagingbindings $DATA/messagingjournal | sed -n  's/.*messageID=\([0-9]*\)\;.*,_HQ_SCHED_DELIVERY=\([0-9]*\),jmsxdeliverycount=\([0-9]*\),.*/\1 \2 \3/p' | while read id hq_sched jmsxdeliverycount
do
    # on a Mac you need to convert the milliseconds time to seconds for the date conversion to work
    if [ "$(uname)" == "Darwin" ]; then
        A=`expr $hq_sched / 1000`
    else
        A=$hq_sched
    fi
    D=`date -r $A`
    echo $id $jmsxdeliverycount $D
done

}

# if we did not get an argument and we cannot find an jboss env var then fail
if test $# -ne 1 && [ -z $JBOSS_HOME ]
then
    usage
    exit 1
fi

if test $# -eq 1 
then
    # we have an argument so we will use that for the location of JBoss
    JB="$1"
else
    JB="$JBOSS_HOME"
fi

# make sure that we can find the jboss installation
if test ! -d $JB
then
    echo "error: JBoss not found at $JB"
    usage
    exit 1
fi

DATA=$JB/standalone/data
BASE=$JB/modules/system/layers/base
JARS="org/hornetq/main/hornetq-server-2.3.5.Final-redhat-2.jar:org/hornetq/main/hornetq-commons-2.3.5.Final-redhat-2.jar:org/hornetq/main/hornetq-journal-2.3.5.Final-redhat-2.jar:org/hornetq/main/hornetq-core-client-2.3.5.Final-redhat-2.jar:org/jboss/logging/main/jboss-logging-3.1.2.GA-redhat-1.jar:org/jboss/netty/main/netty-3.6.6.Final-redhat-1.jar:netty-3.2.6.Final.jar:hornetq-logging-2.2.13.Final.jar"

cd $BASE

# to output all data do this
echo "Raw Data"
outputRaw

# to output only some of the data do this
echo
echo "MessageID Delivery Date"
outputSched

